### ISSUE TITLE
Manage multiple Titles and add a rdfs:label to all works

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#31]
In mapping rules we have the concept of **_not significant titles_**.
In a nutshell, we do not indicate with `ecrm:P102_has_title` titles like 'Sinfonia n. 7 in La maggiore' because it contains parts that are parsed respectively as genre, opus number and key.

example: http://data.doremus.org/expression/81498b00-7a42-395a-9c70-9a1643d9b62c

That means that **we have nothing that can be visualized** for a certain number of works.

My proposal is to add a`rdfs:label` field for each work that contains:
- the same value of `ecrm:P102_has_title`, when exists
- the _not significant title_ otherwise

______________________

## Roadmap

- [x] @pierrechoffe creation of the 4 properties in the ontology
- [ ] each institution, update the mapping rules
- [ ] @pasqLisena, implement the mapping rules

**Comment by pierrechoffe** [comment]
Hi Pasquale,
Is this the problem that was raised already (by Konstantin?) of titles not appearing when they are not significant? We had a discussion about it with Françoise and Frédéric at the time and we consider this was a misunderstanding (of us) in the mapping : titles should *definitely* appear, even when not significant. Any contrary mention should be considered irrelevant.
Therefore, rather than working around the problem, wouldn't it be easier to treat the $144 as a title?
All best,
Pierre

**Comment by rtroncy** [comment]
```rdf:label``` should definitively be a mandatory property for all works (and also for most of the top level entities, although naming event is always tricky).

@pasqLisena Can you point out precisely where this concept of "non significant title" is described in the mapping table? I cannot find it.

**Comment by pasqLisena** [comment]
> Can you point out precisely where this concept of "non significant title" is described in the mapping table? I cannot find it.

@rtroncy In the mapping there are different parts like "Comparer le contenu de XXX avec les termes figurant dans le Tableau des titres non significatifs, ..."
In the practice, we have a [table of genres](https://github.com/DOREMUS-ANR/marc2rdf/blob/c79b7c502893ab6d196574eb7f5c2372d35b5c3a/src/main/resources/GenresBNF.xlsx) and we discard the title if it is in the table.

> rdf:label should definitively be a mandatory property for all works (and also for most of the top level entities, although naming event is always tricky).

Should I create a duplicate of `ecrm:P102_has_title` for each work?

**Comment by manoach** [comment]
Hello,
Indeed, looking at the mapping table, there are only **significant titles** that are assigned to the `P102_has_title property` of `F22_Self_Contained_Expression`. 

From what I understood of this, the **non-significant titles** are stored in the access points because they are composed of : `genre in plural`, `distribution`, `opus` and `key` consecutively.

If we go back to the e-mail of Françoise (27-05-2016), she said: 

> Effectivement, la BnF s'en tient à stricte définition de E35 Title et surtout les exemples qui ne donnent que des titres significatifs.
> Si on devait donner un titre non significatif ce serait "sonate" ou "symphonie" or c'est explicitement exclu de la définition de E35 Title. J'ai toujours été assez réservée sur la typologie des titres, mais pour moi celle-ci permet surtout de qualifier un titre original, un titre traduit, un surnom, ... - ce type de précision.
> Les TUM sont des points d'accès construits (la notion même de "Titre uniforme" renvoie à un titre construit par le catalogueur selon des règles précises), c'est pourquoi ils figurent dans les points d'accès.

In my opinion, it is not necessary to repeat information that already exists in other properties. So for the alignment task, we have to compare the titles (**significant**) and **access points**.

But the problem that arises here: `what is the complexity to build queries by the user in order to have the title of a work`? (In the case where the latter has **non significant title**)

**Comment by pasqLisena** [comment]
> If we go back to the e-mail of Françoise

If I understand well @pierrechoffe's post, they changed idea later.

**Comment by rtroncy** [comment]
Can someone point me to the mapping table where processing significant versus non-significant titles is described?

How often (count) do we have works with significant / non-significant titles? I'm trying to quantify how important is the problem. Bottom line: properties such as ```rdfs:label``` should always be valued for clients that present data.

**Comment by pasqLisena** [comment]
> Can someone point me to the mapping table where processing significant versus non-significant titles is described?

Mapping tables: (search inside for "Tableau des titres non significatifs")
* [BnF](https://drive.google.com/open?id=0B4s5dBwAmhJsUXJrVnVtb19JMTA)
* [PP](https://drive.google.com/open?id=0B_oqgmkXcLOvUjFSdlRUaGRMcEE)

The "Tableau des titres non significatifs" is in practice a table of genres (you can see it [here](https://github.com/DOREMUS-ANR/marc2rdf/blob/c79b7c502893ab6d196574eb7f5c2372d35b5c3a/src/main/resources/GenresBNF.xlsx)).

In the code, we decide if a title should survive (significative) or be rejected (not significative) through [this method](https://github.com/DOREMUS-ANR/marc2rdf/blob/master/src/main/java/org/doremus/marc2rdf/main/Converter.java#L269).

> How often (count) do we have works with significant / non-significant titles? 

If we think about it as "works with a genre as title", you can search for them with:

```sparql
prefix efrbroo: <http://erlangen-crm.org/efrbroo/> 
prefix ecrm:  <http://erlangen-crm.org/current/> 
prefix mus: <http://data.doremus.org/ontology#> 

select count(*) where { 
   ?s a efrbroo:F22_Self-Contained_Expression;
   mus:U12_has_genre ?genre
   MINUS 
     { ?s ecrm:P102_has_title ?title }
 }
```

Result: 14.021 - [see it](http://data.doremus.org/sparql?default-graph-uri=&query=prefix+efrbroo%3A+%3Chttp%3A%2F%2Ferlangen-crm.org%2Fefrbroo%2F%3E+%0D%0Aprefix+ecrm%3A++%3Chttp%3A%2F%2Ferlangen-crm.org%2Fcurrent%2F%3E+%0D%0Aprefix+mus%3A+%3Chttp%3A%2F%2Fdata.doremus.org%2Fontology%23%3E+%0D%0A%0D%0Aselect+count%28*%29+where+%7B+%0D%0A+++%3Fs+a+efrbroo%3AF22_Self-Contained_Expression%3B%0D%0A+++mus%3AU12_has_genre+%3Fgenre%0D%0A+++MINUS+%0D%0A+++++%7B+%3Fs+ecrm%3AP102_has_title+%3Ftitle+%7D%0D%0A+%7D&format=text%2Fhtml&timeout=0&debug=on)

**BUT** your question give me a doubt: you think that we should maintain the distinction _significant-not significant_ and not remove it as @pierrechoffe suggested?

> Bottom line: properties such as rdfs:label should always be valued for clients that present data.

I agree.

**Comment by rtroncy** [comment]
OK, I think I better understand the issue now which can be broken down in separate sub-issues:
* Should we keep this distinction between significant and non-significant titles when populating the value of the ```ecrm:P102_has_title``` property? @pierrechoffe, from [your comment](https://github.com/DOREMUS-ANR/marc2rdf/issues/31#issuecomment-271973696), we understand we should not, but this is not very clear and anyway, if this does not matter anymore, you should modify the mapping tables!
* Assuming that any expression should always have a title, what are the construction rules for populating this title when this a *"titre significatif"* and when this is a *"titre non significatif"*?
* I have also argued earlier on that key entities should have a ```rdfs:label``` property. In the case of expression, should we duplicate the title property as a label?

**Comment by pierrechoffe** [comment]
@rtroncy @pasqLisena 
I agree with you, the mapping table should (and will) be changed !
The question was re-submitted to Françoise and Frédéric, for a clear answer from BnF, so you should get an answer soon (Françoise has a few thousands of emails to treat right now)

**Comment by pasqLisena** [comment]
**_Summary of the discussion of 20/01/2017._**

The ontology is evolving in order to have **4 properties** (hasTitle, hasTUM, hasSubtitle, hasVariantTitle), with 4 different meanings.

The `rdfs:label` will host only **one value** among these (normally TUM or Title) chosen following a **priority order** specified on the mapping rules.

**Comment by pasqLisena** [comment]
I am looking at the source files: we have methods for distinguish between the 4 kind of titles?

**Comment by rtroncy** [comment]
cc @pierrechoffe for the question above!

**Comment by pierrechoffe** [comment]
The group agreed on a restricted list of 4 types of titles, therefore we don't have to type titles, we just use 4 properties. The situation is different for each partner, so it is difficult to answer precisely, maybe the best would be to talk about it at the General Assembly next week. But in principle, all partners are able to distinguish beteween the 4 kinds of titles.
At BnF, it is definitely possible to identify the different types of titles and they solved the initial problem of Uniform Titles not appearing.
One more point :
The `U70 has title` property has been discussed at the last March meeting (where Pasquale was), it is supposed to link to the original title given _by the composer_ , so it is very specific. It was suggested yesterday to rename it `U70 original title` in order to avoid any confusion  with the generic FRBRoo property `P102 has title`.
We also saw yesterday that some titles didn't need a specific DOREMUS property, e.g. the title of a track or of an album, they must be described with the generic property `P102 has title`. I think this will come out very clear from the mapping.
