### ISSUE TITLE
Modeling of Manifestation

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#32]
## RoadMap

- [ ] @pasqLisena + @rtroncy : write down and validate the turtle realized on the base of [examples]( https://drive.google.com/drive/folders/0B_oqgmkXcLOvU2w4N2E1YzhRYVU?ddrp=1&usp=drive_web )
- [ ] @FLERESCHE : realize the mapping rules
- [ ] implement the mapping rules
